wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1645263508
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 14
      4: 3.8.10
      5: 0.12.9
      8:
      - 5
batch_size:
  desc: null
  value: 16
contrast_scheme:
  desc: null
  value: arcface
data_dir:
  desc: null
  value: data/covidx/train
epochs:
  desc: null
  value: 50
img_size:
  desc: null
  value: 480
lr:
  desc: null
  value: 0.0001
lr_sched:
  desc: null
  value: exp
no_batch_norm:
  desc: null
  value: true
patience:
  desc: null
  value: null
run_name:
  desc: null
  value: covid_net_test_contrastive_arcface_2
save_dir:
  desc: null
  value: ./checkpoints
saved_every:
  desc: null
  value: 5
test_dir:
  desc: null
  value: data/covidx/test
val_ratio:
  desc: null
  value: 0.2
