wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1644917130
    t:
      1:
      - 2
      - 3
      - 5
      3:
      - 14
      4: 3.8.10
      5: 0.12.9
      8:
      - 5
