wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1644917026
    t:
      1:
      - 2
      - 3
      - 5
      3:
      - 14
      4: 3.8.10
      5: 0.12.9
      8:
      - 5
batch_size:
  desc: null
  value: 16
data_dir:
  desc: null
  value: data/covidx/train
epochs:
  desc: null
  value: 50
img_size:
  desc: null
  value: 480
lr:
  desc: null
  value: 0.0001
no_batch_norm:
  desc: null
  value: true
patience:
  desc: null
  value: null
run_name:
  desc: null
  value: test_run_14
save_dir:
  desc: null
  value: ./checkpoints
saved_every:
  desc: null
  value: 5
test_dir:
  desc: null
  value: data/covidx/test
val_ratio:
  desc: null
  value: 0.2
